SELECT 'Tên cửa hàng' = CUAHANG.TenCH, 'Số lượng băng chưa trả' = tbTHUECHUATRA.SL FROM CUAHANG
INNER JOIN
(SELECT THUE.MaCH, SL = COUNT(tbCHUATRA.MaBG) FROM THUE
INNER JOIN
(SELECT CTDOTTHUE.DotThue, CTDOTTHUE.MaBG, CTDOTTHUE.NgayTra FROM CTDOTTHUE
WHERE CTDOTTHUE.NgayTra = '') tbCHUATRA
ON THUE.DotThue = tbCHUATRA.DotThue
GROUP BY THUE.MaCH) tbTHUECHUATRA
ON CUAHANG.MaCH = tbTHUECHUATRA.MaCH