SELECT tbTHUE.MaBG, BANGVIDEO.NuocSX FROM BANGVIDEO
INNER JOIN
(SELECT tbDOTTHUE.MaBG, SoLuong = COUNT(tbDOTTHUE.DotThue) FROM 

(SELECT CTDOTTHUE.MaBG, CTDOTTHUE.DotThue, THUE.NgayThue FROM CTDOTTHUE
INNER JOIN THUE
ON CTDOTTHUE.DotThue = THUE.DotThue
WHERE THUE.NgayThue BETWEEN '2/1/00' AND '5/31/00') tbDOTTHUE

GROUP BY
tbDOTTHUE.MaBG) tbTHUE
ON tbTHUE.MaBG = BANGVIDEO.MaBG
WHERE NuocSX='VN'

(SELECT CTDOTTHUE.MaBG, CTDOTTHUE.DotThue, THUE.NgayThue FROM CTDOTTHUE
INNER JOIN THUE
ON CTDOTTHUE.DotThue = THUE.DotThue
WHERE THUE.NgayThue BETWEEN '2/1/00' AND '5/31/00')