SELECT 'Tên Cửa Hàng' = TenCH, 'Số lượng' = Quality FROM

(SELECT THUE.MaCH, Quality = COUNT(THUE.MaCH) FROM THUE
WHERE THUE.NgayThue BETWEEN '04/01/00' AND '04/30/00'
GROUP BY THUE.MaCH) AS tbTHUEQUALITY,
CUAHANG

WHERE CUAHANG.MaCH=tbTHUEQUALITY.MaCH