SELECT TenBG FROM BANGVIDEO INNER JOIN
(SELECT MaBG, CTDOTTHUE.DotThue FROM CTDOTTHUE INNER JOIN
(SELECT DotThue FROM THUE
WHERE NgayThue = '02/16/00') tbTHUE
ON CTDOTTHUE.DotThue = tbTHUE.DotTHUE) tbMABG
ON
BANGVIDEO.MaBG = tbMABG.MaBG AND TheLoai = N'HH'

SELECT 'Tên bãng' = BANGVIDEO.TenBG FROM THUE
INNER JOIN CTDOTTHUE
ON THUE.DotThue = CTDOTTHUE.DotThue
INNER JOIN BANGVIDEO
ON CTDOTTHUE.MaBG = BANGVIDEO.MaBG
WHERE THUE.NgayThue = '02/16/00' AND BANGVIDEO.TheLoai = N'HH'