SELECT N'Tên cửa hàng'=tbTenCH.TenCH, N'Băng chưa được thuê' = BANGVIDEO.TenBG FROM BANGVIDEO
INNER JOIN
(SELECT CUAHANG.TenCH, MaBG FROM CUAHANG
INNER JOIN
(SELECT PHANPHOI.MaCH, PHANPHOI.MaBG FROM PHANPHOI
WHERE PHANPHOI.MaBG NOT IN
(SELECT DISTINCT CTDOTTHUE.MaBG FROM CTDOTTHUE)) tbKOTHUE
ON tbKOTHUE.MaCH = CUAHANG.MaCH) tbTenCH
ON tbTenCH.MaBG = BANGVIDEO.MaBG