SELECT 'Tên cửa hàng' = CUAHANG.TenCH, 'Tên băng' = tbCHBG.TenBG, 'Số lượng' = SUM(tbCHBG.SLBG) FROM CUAHANG
INNER JOIN
(SELECT PHANPHOI.MaCH, BANGVIDEO.TenBG, PHANPHOI.SLBG FROM PHANPHOI
INNER JOIN BANGVIDEO
ON PHANPHOI.MaBG = BANGVIDEO.MaBG) tbCHBG
ON CUAHANG.MaCH = tbCHBG.MaCH
GROUP BY CUAHANG.TenCH, tbCHBG.TenBG
WITH ROLLUP