SELECT 'Tên băng' = TenBG FROM BANGVIDEO,
(SELECT MaBG FROM CTDOTTHUE,
(SELECT THUE.DotThue FROM THUE
WHERE THUE.KHG = N'Trần Đình Nguyên') AS tbTHUECUS
WHERE tbTHUECUS.DotThue = CTDOTTHUE.DotThue) AS tbDOTTHUECUS
WHERE tbDOTTHUECUS.MaBG = BANGVIDEO.MaBG


SELECT THUE.KHG, THUE.DotThue, CTDOTTHUE.MaBG, BANGVIDEO.TenBG FROM THUE
INNER JOIN CTDOTTHUE
ON THUE.DotThue =CTDOTTHUE.DotThue
INNER JOIN BANGVIDEO
ON CTDOTTHUE.MaBG = BANGVIDEO.MaBG
WHERE THUE.KHG = N'Trần Đình Nguyên'