SELECT TenCH,NgayThue, SoLuong = COUNT(NgayThue) FROM THUE
INNER JOIN
(SELECT CUAHANG.TenCH, tbDOTTHUE.MaBG,tbDOTTHUE.DotThue FROM CUAHANG
INNER JOIN
(SELECT CTDOTTHUE.DotThue,CTDOTTHUE.MaBG,PHANPHOI.MaCH FROM CTDOTTHUE
INNER JOIN PHANPHOI
ON
CTDOTTHUE.MaBG = PHANPHOI.MaBG) tbDOTTHUE
ON CUAHANG.MaCH = tbDOTTHUE.MaCH) tbCUAHANG
ON tbCUAHANG.DotThue =THUE.DotThue
GROUP BY TenCH,NgayThue
WITH ROLLUP