SELECT CUAHANG.TenCH, CUAHANG.DCCH FROM CUAHANG,
(SELECT MaCH, Quality FROM 
(SELECT MaCH, Quality = COUNT(MaBG) FROM
(SELECT THUE.MaCH,CTDOTTHUE.MaBG FROM THUE
INNER JOIN CTDOTTHUE
ON THUE.DotThue = CTDOTTHUE.DotThue) tbTHUECTDT
GROUP BY MaCH) tbQuality,

(SELECT MQuality = MAX(Quality) FROM CUAHANG,
(SELECT MaCH, Quality = COUNT(MaBG) FROM
(SELECT THUE.MaCH,CTDOTTHUE.MaBG FROM THUE
INNER JOIN CTDOTTHUE
ON THUE.DotThue = CTDOTTHUE.DotThue) tbTHUECTDT
GROUP BY MaCH) tbQuality) tbMax

WHERE tbQuality.Quality = tbMax.MQuality) tbMaCHMax

WHERE tbMaCHMax.MaCH = CUAHANG.MaCH
