SELECT 'Tên cửa hàng' = CUAHANG.TenCH,'Thể loại' = tbCHTL.TL,'Số lượng' = SUM(tbCHTL.SL) FROM CUAHANG
INNER JOIN 
(SELECT  CH = PHANPHOI.MaCH, BANGVIDEO.MaBG, TL = BANGVIDEO.TheLoai, SL = PHANPHOI.SLBG  FROM BANGVIDEO
INNER JOIN PHANPHOI
ON BANGVIDEO.MaBG = PHANPHOI.MaBG) tbCHTL
ON CUAHANG.MaCH = tbCHTL.CH
GROUP BY CUAHANG.TenCH, tbCHTL.TL
WITH ROLLUP