SELECT TenBG FROM BANGVIDEO INNER JOIN
(SELECT MaBG, CTDOTTHUE.DotThue FROM CTDOTTHUE INNER JOIN
(SELECT DotThue FROM THUE
WHERE NgayThue = '02/16/00') tbTHUE
ON CTDOTTHUE.DotThue = tbTHUE.DotTHUE) tbMABG
ON
BANGVIDEO.MaBG = tbMABG.MaBG AND TheLoai = N'HH'
