CREATE VIEW View1 AS
SELECT TenCH, TenBG, TheLoai, NuocSX, SLGoc, SLBG
FROM PHANPHOI JOIN BANGVIDEO
ON PHANPHOI.MaBG = BANGVIDEO.MaBG
JOIN CUAHANG ON PHANPHOI.MaCH = CUAHANG.MaCH
WHERE TenCH = N'Cửa hàng Dạ Lý Hương' AND TheLoai IN ('HH','CN')

DROP VIEW View1

SELECT * FROM View1
